type ImagesRouteType = {
  [key: string]: string;
};

const ImagesRoute: ImagesRouteType = {
  avatar_black_blue_bg: require("./Avatars/avatar_black_blue_bg.svg").default,
  avatar_black_green_bg: require("./Avatars/avatar_black_green_bg.svg").default,
  avatar_black_grey_bg: require("./Avatars/avatar_black_grey_bg.svg").default,
  avatar_black_orange_bg: require("./Avatars/avatar_black_orange_bg.svg")
    .default,
  avatar_black_pink_bg: require("./Avatars/avatar_black_pink_bg.svg").default,
  avatar_black_purple_bg: require("./Avatars/avatar_black_purple_bg.svg")
    .default,
  avatar_black_red_bg: require("./Avatars/avatar_black_red_bg.svg").default,
  avatar_black_yellow_bg: require("./Avatars/avatar_black_yellow_bg.svg")
    .default,
  avatar_large_blue: require("./Avatars/avatar_large_blue.svg").default,
  avatar_large_green: require("./Avatars/avatar_large_green.svg").default,
  avatar_large_orange: require("./Avatars/avatar_large_orange.svg").default,
  avatar_large_pink: require("./Avatars/avatar_large_pink.svg").default,
  avatar_large_purple: require("./Avatars/avatar_large_purple.svg").default,
  avatar_large_red: require("./Avatars/avatar_large_red.svg").default,
  avatar_large_white: require("./Avatars/avatar_large_white.svg").default,
  avatar_large_yellow: require("./Avatars/avatar_large_yellow.svg").default,
  avatar_regular_blue: require("./Avatars/avatar_regular_blue.svg").default,
  avatar_regular_green: require("./Avatars/avatar_regular_green.svg").default,
  avatar_regular_orange: require("./Avatars/avatar_regular_orange.svg").default,
  avatar_regular_pink: require("./Avatars/avatar_regular_pink.svg").default,
  avatar_regular_purple: require("./Avatars/avatar_regular_purple.svg").default,
  avatar_regular_red: require("./Avatars/avatar_regular_red.svg").default,
  avatar_regular_white: require("./Avatars/avatar_regular_white.svg").default,
  avatar_regular_yellow: require("./Avatars/avatar_regular_yellow.svg").default,
  avatar_small_blue: require("./Avatars/avatar_small_blue.svg").default,
  avatar_small_green: require("./Avatars/avatar_small_green.svg").default,
  avatar_small_orange: require("./Avatars/avatar_small_orange.svg").default,
  avatar_small_pink: require("./Avatars/avatar_small_pink.svg").default,
  avatar_small_purple: require("./Avatars/avatar_small_purple.svg").default,
  avatar_small_red: require("./Avatars/avatar_small_red.svg").default,
  avatar_small_white: require("./Avatars/avatar_small_white.svg").default,
  avatar_small_yellow: require("./Avatars/avatar_small_yellow.svg").default,
  avatar_XL_blue: require("./Avatars/avatar_XL_blue.svg").default,
  avatar_XL_green: require("./Avatars/avatar_XL_green.svg").default,
  avatar_XL_orange: require("./Avatars/avatar_XL_orange.svg").default,
  avatar_XL_pink: require("./Avatars/avatar_XL_pink.svg").default,
  avatar_XL_purple: require("./Avatars/avatar_XL_purple.svg").default,
  avatar_XL_red: require("./Avatars/avatar_XL_red.svg").default,
  avatar_XL_white: require("./Avatars/avatar_XL_white.svg").default,
  avatar_XL_yellow: require("./Avatars/avatar_XL_yellow.svg").default,
  avatar_XS_blue: require("./Avatars/avatar_XS_blue.svg").default,
  avatar_XS_green: require("./Avatars/avatar_XS_green.svg").default,
  avatar_XS_orange: require("./Avatars/avatar_XS_orange.svg").default,
  avatar_XS_pink: require("./Avatars/avatar_XS_pink.svg").default,
  avatar_XS_purple: require("./Avatars/avatar_XS_purple.svg").default,
  avatar_XS_red: require("./Avatars/avatar_XS_red.svg").default,
  avatar_XS_white: require("./Avatars/avatar_XS_white.svg").default,
  avatar_XS_yellow: require("./Avatars/avatar_XS_yellow.svg").default,
  close_side_bar_icon: require("./Icons/close_side_bar_icon.svg").default,
  dark_mode_icon: require("./Icons/dark_mode_icon.svg").default,
  dash_board_icon: require("./Icons/dash_board_icon.svg").default,
  home_icon: require("./Icons/home_icon.svg").default,
  log_out_icon: require("./Icons/log_out_icon.svg").default,
  medal_big: require("./Icons/medal_big.png").default,
  medal_icon: require("./Icons/medal_icon.svg").default,
  profile_icon: require("./Icons/profile_icon.svg").default,
  setting_icon: require("./Icons/setting_icon.svg").default,
  trophy_big: require("./Icons/trophy_big.png"),
  trophy_icon: require("./Icons/trophy_icon.svg").default,
  upgrade_Icon: require("./Icons/upgrade_Icon.svg").default,
  flag_button: require("./Icons/flag_button.svg").default,
  send_button: require("./Icons/send_button.svg").default,
  cancel_button: require("./Icons/cancel_button.svg").default,
  mic_button: require("./Icons/mic_button.svg").default,
  not_mic_button: require("./Icons/not_mic_button.svg").default,
  logo_icon: require("./Icons/logo_icon.svg").default,

  cancel: require("./test/cancel.png").default,
  choiceBar: require("./test/choiceBar.png").default,
  choiceWrap: require("./test/choiceWrap.png").default,
  light_mode_icon: require("./Icons/light_mode_icon.svg").default,
  IMG_7009_Enhanced_NR: require("./test/IMG_7009-Enhanced-NR.jpg").default,

  upload_wh_icon: require("./Icons/upload_wh_icon.png"),
};

export default ImagesRoute;
